### ISSUE TITLE
Replay single track function broken with this enabled.

### ISSUE THREAD

**Issue by NocFA** [Faywyrr/Better-DeezerRPC#3]
The Deezer replay function has 3 forms, off, on and replays a single track.
The latter of which (replay single track) does not work once this application is installed.

Replication:
- Download Deezer desktop and try to enable the feature, it works as intended.
- Now, install the better Deezer RPC application
- Try to replicate the same working functionality
- See as Deezer does not repeat the track, instead, the replay mode changes back to `on` state rather than replay single track.

OS - Windows 11 21H2 Enterprise
Deezer Version - 5.30.90 / 5.30.80 (issue  happened with both versions)

**Comment by Faywyrr** [comment]
Thank you for your issue!
I will fix this
