### ISSUE TITLE
No longer functions with latest update on Windows.

### ISSUE THREAD

**Issue by NocFA** [Faywyrr/Better-DeezerRPC#4]
Since the last update or so, I just get a white screen upon loading Deezer after patching it.
It appears they broke it again, and, as you have the best DeezerRPC implementation that exists out there a hot fix would be much appreciated, I shall send you a coffee if required.

Thank you sir!

**Comment by NocFA** [comment]
I checked back in, it now works, again? not sure how, but, I'm thankful it does, if this ever breaks for good, please come back to patch it, I will pay you good sir! :P

**Comment by Faywyrr** [comment]
I'm sorry, I didn't see your request! If it doesn't work, I'll correct it as soon as possible.
